platform :ios, '14.1'

project 'mdmr.xcodeproj'

target 'mdmr' do
  use_frameworks!
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
    end
  end
end
